apiVersion: v1
kind: Service
metadata:
  name: python-login-service
  labels:
    app: python-login
spec:
  type: LoadBalancer        # Use NodePort if running locally (e.g., minikube)
  selector:
    app: python-login
  ports:
    - protocol: TCP
      port: 8082            # external service port
      targetPort: 8082      # container port
      nodePort: 30082       # (optional) NodePort for local testing
